package com.ccji.demo.wsclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "HelloService", targetNamespace = "http://webservice.ccji.com/")
public interface HelloService {

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "sayHello", targetNamespace = "http://webservice.ccji.com/", className = "com.ccji.demo.cfxclient.SayHello")
	@ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://webservice.ccji.com/", className = "com.ccji.demo.cfxclient.SayHelloResponse")
	public String sayHello(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

}
